services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "Asia/Kathmandu"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "unbound#5335"
      FTLCONF_webserver_port: "80,443s"
      FTLCONF_webserver_api_password: "admin"
    volumes:
      - ../../data/pihole:/etc/pihole
    restart: unless-stopped
    depends_on:
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
