include:
  - ./services/unbound/unbound.yml
  - ./services/pi-hole/pi-hole.yml
  - ./services/mysql/mysql.yml
  - ./services/redis/redis.yml
  - ./services/redisinsight/redisinsight.yml
  - ./services/dynamodb/dynamodb.yml
  - ./services/dynamodb-dashboard/dynamodb-dashboard.yml
  - ./services/phpmyadmin/phpmyadmin.yml
  - ./services/minio/minio.yml
  - ./services/actual/actual.yml
  - ./services/nextcloud/nextcloud.yml
