services:
  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf
      - ./unbound/root.hints:/etc/unbound/root.hints
    restart: unless-stopped
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
