services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    volumes:
      - ../../data/mysql:/var/lib/mysql
    ports:
      - 3306:3006
