services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    depends_on:
      - mysql
      - redis
    volumes:
      - ../../data/nextcloud/apps:/var/www/html/custom_apps
      - ../../data/nextcloud/config:/var/www/html/config
      - ../../data/nextcloud/data:/var/www/html/data
    environment:
      TZ: "Asia/Kathmandu"
      MYSQL_HOST: mysql
      REDIS_HOST: redis
