services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    restart: always
    volumes:
      - ../../data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
