services:
  minio:
    container_name: minio
    image: minio/minio:latest
    network_mode: host
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ../../data/minio:/data
