services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ../../data/redis:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
