services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      APACHE_PORT: 8081
    restart: always
    ports:
      - 8081:8081
